CREATE TABLE episodes (
    id SERIAL PRIMARY KEY,
    number INT NOT NULL,
    name VARCHAR,
    serial_id INTEGER NOT NULL REFERENCES serials(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);