-- Your SQL goes here
CREATE TABLE scrapers (
    id SERIAL PRIMARY KEY,
    target_url VARCHAR NOT NULL
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
